# Generated by Django 5.2.12 on 2026-04-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('pintura', 'Pintura'), ('lija', 'Lija'), ('masilla', 'Masilla'), ('soldadura', 'Soldadura'), ('quimico', 'Químico'), ('herramienta', 'Herramienta'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(default='unidad', help_text='Ej: litro, unidad, kilo, metro', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5, help_text='Alerta cuando el stock baje de este número', max_digits=10)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Inventario',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
