# Generated by Django 5.2.12 on 2026-04-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('camioneta', 'Camioneta'), ('otro', 'Otro')], default='sedan', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['marca'],
            },
        ),
    ]
