# Generated by Django 5.2.12 on 2026-04-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.CharField(choices=[('vehiculo', 'Vehículo'), ('motocicleta', 'Motocicleta')], default='vehiculo', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='gasolina',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de gasolina, de 0 a 100', max_digits=5, verbose_name='Gasolina en tanque (%)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kilometraje (km)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_moto',
            field=models.CharField(blank=True, choices=[('estandar', 'Estándar'), ('chopper', 'Chopper'), ('deportivo', 'Deportivo'), ('cuadratrack', 'Cuadratrack'), ('otro_moto', 'Otro')], max_length=20, null=True, verbose_name='Tipo de motocicleta'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedán'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('hatchback', 'Hatchback'), ('camioneta', 'Camioneta'), ('minibus', 'Minibús'), ('vagoneta', 'Vagoneta'), ('automovil', 'Automóvil'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de vehículo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.IntegerField(verbose_name='Año'),
        ),
    ]
