# Generated by Django 5.2.12 on 2026-04-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ci',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Carnet de Identidad'),
        ),
    ]
