# Generated by Django 5.2.12 on 2026-04-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ci',
            field=models.CharField(max_length=20, unique=True, verbose_name='Carnet de Identidad'),
        ),
    ]
