# Generated by Django 5.2.12 on 2026-04-30 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de recepción del vehículo'),
        ),
        migrations.AddField(
            model_name='orden',
            name='primer_adelanto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primer adelanto (Bs.)'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tecnico',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado'),
        ),
        migrations.CreateModel(
            name='HistorialAdelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('registro', 'Registro'), ('edicion', 'Edición')], default='registro', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_adelantos', to='ordenes.orden')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de adelanto',
                'verbose_name_plural': 'Historial de adelantos',
                'ordering': ['-fecha'],
            },
        ),
    ]
